### ISSUE TITLE
error, probably after python upgrade on host

### ISSUE THREAD

**Issue by hartmark** [curzon01/mqtt2sql#18]
I have noticed that my mqtt2sql service has started generating errors.

First I got these errors:
```
Jan 09 02:17:17 staropramen systemd[1]: Started mqtt2sql.service.
Jan 09 02:17:17 staropramen mqtt2sql.py[12599]: No module named 'configargparse'. Try 'python -m pip install 'configargparse'' to install
Jan 09 02:17:17 staropramen systemd[1]: mqtt2sql.service: Main process exited, code=exited, status=9/n/a
Jan 09 02:17:17 staropramen systemd[1]: mqtt2sql.service: Failed with result 'exit-code'.
Jan 09 02:17:27 staropramen systemd[1]: mqtt2sql.service: Scheduled restart job, restart counter is at 107.
Jan 09 02:17:27 staropramen systemd[1]: Stopped mqtt2sql.service.
```
i tried running the install as suggested but still same error, but I ran it with sudo I'm getting these errors instead:

```
Jan 09 02:17:27 staropramen systemd[1]: Started mqtt2sql.service.
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: 2022-01-09 02:17:28: mqtt2sql.py[12692] v2.4.0041 start
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: 2022-01-09 02:18:19: mqtt2sql.py[12692] v2.4.0041 end
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: 2022-01-09 02:18:19: mqtt2sql.py[12692] v2.4.0041 end
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: Traceback (most recent call last):
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:   File "/usr/lib/python3.10/threading.py", line 1560, in _shutdown
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:     lock.acquire()
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:   File "/home/markus/bin/mqtt2sql.py", line 851, in _exitus
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:     self.exitus(signal_, 'signal {}#{}'.format(self._signalname(signal_), signal_))
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:   File "/home/markus/bin/mqtt2sql.py", line 872, in exitus
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]:     sys.exit(status)
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: SystemExit: 0
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: 2022-01-09 02:18:19: mqtt2sql.py[12692] v2.4.0041 end
Jan 09 02:18:19 staropramen mqtt2sql.py[12692]: 2022-01-09 02:18:19: mqtt2sql.py[12692] v2.4.0041 end
Jan 09 02:18:19 staropramen systemd[1]: mqtt2sql.service: Deactivated successfully.
Jan 09 02:18:29 staropramen systemd[1]: mqtt2sql.service: Scheduled restart job, restart counter is at 108.
Jan 09 02:18:29 staropramen systemd[1]: Stopped mqtt2sql.service.

```

**Comment by hartmark** [comment]
seems that this error was due to the mariadb being down. So restarting mariadb solved this issue, perhaps a better error message could be written in the logs?

**Comment by curzon01** [comment]
you used an older version, v2.4.0042 is current
